### PR TITLE
Modify color scheme to be more consistent with the base16 ecosystem

### PR DESCRIPTION
**Pull request by gnsfujiwara**
as a base16 user, I think the colors didn't fit very well with the rest of the templates, I think this way it was better.

### CODE REVIEW

**Comment by JamyGolden** [comment]
@gnsfujiwara there are some conflicts, can you update the PR. The github actions file has been created, so if you remove that pull from upstream and re-run the builder on this template, things should be good. I would do those changes for you but I'm unable to edit this PR. (also note the change from `master` to `main` for this repo)

**Comment by JamyGolden** [comment]
@gnsfujiwara if you add me as a contributor to your forked repo I can fix the conflicts on this PR for you.

**Comment by gnsfujiwara** [comment]
Ok, i've added you as a contributor

**Comment by JamyGolden** [comment]
@gnsfujiwara I didn't have the permissions to change anything in your repo it seems, but I created a branch on this repo with your changes. One important thing to note about this PR is that is looking at your `master` branch, even though currently that branch doesn't exist on your github repo.

You can get this PR to reflect your `master` branch by doing the following:

```bash
$ git checkout main # Make sure you're on the main branch
$ git remote add upstream https://github.com/tinted-theming/base16-dunst.git # If you haven't already done this
$ git fetch # fetch the upstream data
$ git br -D master # Delete your local version of master branch
$ git checkout -b master # Create a new version of local master branch
$ git reset --hard upstream/jamy/feature/gnsfujiwara # Make master equal to the branch I made
$ git push --force origin master # You may not need the `--force`, but if you have that branch on your github repo, that will overwrite it
```

Once you've done that this PR should be updated. 

Alternatively, if you don't want to work off of the old `master` branch (and keep this PR closed), you could create a new PR using a `feature/modify-color-scheme` branch by doing this:

```
$ git checkout -b feature/modify-color-scheme
$ git remote add upstream https://github.com/tinted-theming/base16-dunst.git
$ git fetch
$ git reset --hard upstream/jamy/feature/gnsfujiwara 
$ git push
```

And then create a new PR looking at that new `feature/modify-color-scheme` branch.

**Pull request closed without merging**
